### ISSUE TITLE
Bad Reference to ThreadedStorage

### ISSUE THREAD

**Issue by goakley** [Yelp/py_zipkin#104]
`ThreadedStorage` tries to reference the nonexistent `_is_transport_configured`.

Version: `0.14.1`

Example of error:
```
Traceback (most recent call last):
  File "/tmp/workspace/verify-python-lib/tests/test_tracing.py", line 56, in test_zipkin_tracer_no_init
    pass
  File "/tmp/workspace/verify-python-lib/env2/local/lib/python2.7/site-packages/py_zipkin/zipkin.py", line 431, in __exit__
    self.stop(_exc_type, _exc_value, _exc_traceback)
  File "/tmp/workspace/verify-python-lib/env2/local/lib/python2.7/site-packages/py_zipkin/zipkin.py", line 446, in stop
    if not self._span_storage.is_transport_configured():
  File "/tmp/workspace/verify-python-lib/env2/local/lib/python2.7/site-packages/py_zipkin/storage.py", line 62, in is_transport_configured
    return self._is_transport_configured
AttributeError: 'ThreadedStorage' object has no attribute '_is_transport_configured'
```

**Comment by drolando** [comment]
`ThreadedStorage` needs to extend `SpanStorage` and if you override the init function also call `super(ThreadedStorage, self).__init__()`.

**Comment by drolando** [comment]
@goakley did that fix your problem?

**Comment by goakley** [comment]
Brilliant, thanks @drolando !
